select p_brand, p_type, p_size, count(distinct ps_suppkey) as supplier_cnt
from
  denorm_cached
where
  p_brand <> 'Brand#45' and 
    p_size = 49 or p_size = 14 or p_size = 23 or
    p_size = 45 or p_size = 19 or p_size = 3 or
    p_size = 36 or p_size = 9
    and not s_comment like '%Customer%Complaints%'
    and not p_type like 'MEDIUM POLISHED%'
group by p_brand, p_type, p_size
order by supplier_cnt desc, p_brand, p_type, p_size;
