select
  sum(l_extendedprice) / 7.0 as avg_yearly
from
  (select l_quantity, l_extendedprice, t_avg_quantity from
    (select l_partkey as t_partkey, 0.2 * avg(l_quantity) as t_avg_quantity
     from
       denorm_cached
     group by l_partkey) t
    join 
    (select l_quantity, l_partkey, l_extendedprice
      from
        denorm_cached
      where
        p_brand = 'Brand#23'
        and p_container = 'MED BOX') b on b.l_partkey = t.t_partkey) c
where l_quantity < t_avg_quantity;

